// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguageBundle } from '../src/types.js'
import { lazy } from '../src/bundle-helpers.js'

export const bundledLanguages: LanguageBundle = {
  "bash": lazy("bash", ["sh"], () => import("../langs/bash.js")),
  "comment": lazy("comment", [], () => import("../langs/comment.js")),
  "csharp": lazy("csharp", ["c#"], () => import("../langs/csharp.js")),
  "diff": lazy("diff", [], () => import("../langs/diff.js")),
  "dockerfile": lazy("dockerfile", ["docker"], () => import("../langs/dockerfile.js")),
  "elixir": lazy("elixir", [], () => import("../langs/elixir.js")),
  "erlang": lazy("erlang", [], () => import("../langs/erlang.js")),
  "go": lazy("go", [], () => import("../langs/go.js")),
  "graphql": lazy("graphql", [], () => import("../langs/graphql.js")),
  "http": lazy("http", [], () => import("../langs/http.js")),
  "java": lazy("java", [], () => import("../langs/java.js")),
  "javascript": lazy("javascript", ["js","jsx"], () => import("../langs/javascript.js")),
  "json": lazy("json", [], () => import("../langs/json.js")),
  "kotlin": lazy("kotlin", [], () => import("../langs/kotlin.js")),
  "nginx": lazy("nginx", [], () => import("../langs/nginx.js")),
  "php": lazy("php", [], () => import("../langs/php.js")),
  "protobuf": lazy("protobuf", [], () => import("../langs/protobuf.js")),
  "python": lazy("python", [], () => import("../langs/python.js")),
  "regex": lazy("regex", [], () => import("../langs/regex.js")),
  "ruby": lazy("ruby", [], () => import("../langs/ruby.js")),
  "rust": lazy("rust", [], () => import("../langs/rust.js")),
  "scala": lazy("scala", [], () => import("../langs/scala.js")),
  "sql": lazy("sql", [], () => import("../langs/sql.js")),
  "toml": lazy("toml", [], () => import("../langs/toml.js")),
  "typescript": lazy("typescript", ["ts"], () => import("../langs/typescript.js")),
  "xml": lazy("xml", [], () => import("../langs/xml.js")),
  "yaml": lazy("yaml", [], () => import("../langs/yaml.js")),
  "plaintext": lazy("plaintext", ["text","txt","plain"], () => import("../langs/plaintext.js")),
}
