// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguageBundle } from '../src/types.js'
import { lazy } from '../src/bundle-helpers.js'

export const bundledLanguages: LanguageBundle = {
  "bash": lazy("bash", ["sh"], () => import("../langs/bash.js")),
  "comment": lazy("comment", [], () => import("../langs/comment.js")),
  "diff": lazy("diff", [], () => import("../langs/diff.js")),
  "ini": lazy("ini", [], () => import("../langs/ini.js")),
  "xml": lazy("xml", [], () => import("../langs/xml.js")),
  "json": lazy("json", [], () => import("../langs/json.js")),
  "markdown": lazy("markdown", [], () => import("../langs/markdown.js")),
  "markdown_inline": lazy("markdown_inline", [], () => import("../langs/markdown_inline.js")),
  "regex": lazy("regex", [], () => import("../langs/regex.js")),
  "toml": lazy("toml", [], () => import("../langs/toml.js")),
  "yaml": lazy("yaml", [], () => import("../langs/yaml.js")),
  "plaintext": lazy("plaintext", ["text","txt","plain"], () => import("../langs/plaintext.js")),
}
