// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguageBundle } from '../src/types.js'
import { lazy } from '../src/bundle-helpers.js'

export const bundledLanguages: LanguageBundle = {
  "asm": lazy("asm", ["assembly"], () => import("../langs/asm.js")),
  "bash": lazy("bash", ["sh"], () => import("../langs/bash.js")),
  "c": lazy("c", [], () => import("../langs/c.js")),
  "cmake": lazy("cmake", [], () => import("../langs/cmake.js")),
  "comment": lazy("comment", [], () => import("../langs/comment.js")),
  "cpp": lazy("cpp", ["c++"], () => import("../langs/cpp.js")),
  "diff": lazy("diff", [], () => import("../langs/diff.js")),
  "go": lazy("go", [], () => import("../langs/go.js")),
  "json": lazy("json", [], () => import("../langs/json.js")),
  "llvm": lazy("llvm", [], () => import("../langs/llvm.js")),
  "make": lazy("make", [], () => import("../langs/make.js")),
  "regex": lazy("regex", [], () => import("../langs/regex.js")),
  "rust": lazy("rust", [], () => import("../langs/rust.js")),
  "toml": lazy("toml", [], () => import("../langs/toml.js")),
  "wat": lazy("wat", ["wasm","webassembly"], () => import("../langs/wat.js")),
  "yaml": lazy("yaml", [], () => import("../langs/yaml.js")),
  "zig": lazy("zig", [], () => import("../langs/zig.js")),
  "plaintext": lazy("plaintext", ["text","txt","plain"], () => import("../langs/plaintext.js")),
}
