// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguageBundle } from '../src/types.js'
import { lazy } from '../src/bundle-helpers.js'

export const bundledLanguages: LanguageBundle = {
  "astro": lazy("astro", [], () => import("../langs/astro.js")),
  "bash": lazy("bash", ["sh"], () => import("../langs/bash.js")),
  "comment": lazy("comment", [], () => import("../langs/comment.js")),
  "css": lazy("css", [], () => import("../langs/css.js")),
  "diff": lazy("diff", [], () => import("../langs/diff.js")),
  "dockerfile": lazy("dockerfile", ["docker"], () => import("../langs/dockerfile.js")),
  "graphql": lazy("graphql", [], () => import("../langs/graphql.js")),
  "heex": lazy("heex", [], () => import("../langs/heex.js")),
  "html": lazy("html", [], () => import("../langs/html.js")),
  "javascript": lazy("javascript", ["js","jsx"], () => import("../langs/javascript.js")),
  "json": lazy("json", [], () => import("../langs/json.js")),
  "markdown": lazy("markdown", [], () => import("../langs/markdown.js")),
  "markdown_inline": lazy("markdown_inline", [], () => import("../langs/markdown_inline.js")),
  "regex": lazy("regex", [], () => import("../langs/regex.js")),
  "scss": lazy("scss", [], () => import("../langs/scss.js")),
  "sql": lazy("sql", [], () => import("../langs/sql.js")),
  "svelte": lazy("svelte", [], () => import("../langs/svelte.js")),
  "toml": lazy("toml", [], () => import("../langs/toml.js")),
  "tsx": lazy("tsx", [], () => import("../langs/tsx.js")),
  "typescript": lazy("typescript", ["ts"], () => import("../langs/typescript.js")),
  "vue": lazy("vue", [], () => import("../langs/vue.js")),
  "xml": lazy("xml", [], () => import("../langs/xml.js")),
  "yaml": lazy("yaml", [], () => import("../langs/yaml.js")),
  "plaintext": lazy("plaintext", ["text","txt","plain"], () => import("../langs/plaintext.js")),
}
