[workspace]
resolver = "2"
members = ["crates/*", "packages/elixir/lumis/native/lumis_nif"]

[workspace.package]
edition = "2021"
rust-version = "1.91"
license = "MIT"
homepage = "https://lumis.sh"
repository = "https://github.com/leandrocp/lumis"
authors = ["Leandro Pereira <leandro@leandro.io>"]

[patch.crates-io]
lumis = { path = "crates/lumis" }
lumis-core = { path = "crates/lumis-core" }
lumis-build = { path = "crates/lumis-build" }

[profile.release]
lto = true
codegen-units = 1
strip = true
