[github]
owner = "leandrocp"
repo = "lumis"

[changes]
ignore_conventional_commits = true

[packages.cargo-lumis]
versioned_files = ["crates/lumis/Cargo.toml"]
changelog = "crates/lumis/CHANGELOG.md"

[packages.cargo-lumis-core]
versioned_files = [
  "crates/lumis-core/Cargo.toml",
  { path = "crates/lumis/Cargo.toml", dependency = "lumis-core" },
  { path = "crates/lumis-cli/Cargo.toml", dependency = "lumis-core" },
]
changelog = "crates/lumis-core/CHANGELOG.md"

[packages.cargo-lumis-build]
versioned_files = [
  "crates/lumis-build/Cargo.toml",
  { path = "crates/lumis/Cargo.toml", dependency = "lumis-build" },
  { path = "crates/lumis-cli/Cargo.toml", dependency = "lumis-build" },
]
changelog = "crates/lumis-build/CHANGELOG.md"

[packages.cargo-lumis-cli]
versioned_files = ["crates/lumis-cli/Cargo.toml"]
changelog = "crates/lumis-cli/CHANGELOG.md"

[packages.npm-lumis]
versioned_files = [
  "packages/javascript/lumis/package.json",
  { path = "packages/javascript/react/package.json", dependency = "@lumis-sh/lumis" },
  { path = "packages/javascript/markdown-it-lumis/package.json", dependency = "@lumis-sh/lumis" },
  { path = "packages/javascript/rehype-lumis/package.json", dependency = "@lumis-sh/lumis" },
]
changelog = "packages/javascript/lumis/CHANGELOG.md"

[packages.npm-markdown-it-lumis]
versioned_files = ["packages/javascript/markdown-it-lumis/package.json"]
changelog = "packages/javascript/markdown-it-lumis/CHANGELOG.md"

[packages.npm-rehype-lumis]
versioned_files = ["packages/javascript/rehype-lumis/package.json"]
changelog = "packages/javascript/rehype-lumis/CHANGELOG.md"

[packages.npm-react]
versioned_files = ["packages/javascript/react/package.json"]
changelog = "packages/javascript/react/CHANGELOG.md"

[packages.npm-themes]
versioned_files = [
  "packages/javascript/themes/package.json",
  { path = "packages/javascript/lumis/package.json", dependency = "@lumis-sh/themes" },
]
changelog = "packages/javascript/themes/CHANGELOG.md"

[packages.npm-wasm-bundle-web]
versioned_files = ["packages/javascript/wasm-bundle-web/package.json"]
changelog = "packages/javascript/wasm-bundle-web/CHANGELOG.md"

[packages.npm-wasm-bundle-web-extra]
versioned_files = ["packages/javascript/wasm-bundle-web-extra/package.json"]
changelog = "packages/javascript/wasm-bundle-web-extra/CHANGELOG.md"

[packages.npm-wasm-bundle-system]
versioned_files = ["packages/javascript/wasm-bundle-system/package.json"]
changelog = "packages/javascript/wasm-bundle-system/CHANGELOG.md"

[packages.npm-wasm-bundle-backend]
versioned_files = ["packages/javascript/wasm-bundle-backend/package.json"]
changelog = "packages/javascript/wasm-bundle-backend/CHANGELOG.md"

[packages.npm-wasm-bundle-full]
versioned_files = ["packages/javascript/wasm-bundle-full/package.json"]
changelog = "packages/javascript/wasm-bundle-full/CHANGELOG.md"

[packages.hex-lumis]
versioned_files = [
  { path = "packages/elixir/lumis/mix.exs", regex = '@version "(?<version>\d+\.\d+\.\d+(?:[-+][^"]+)?)"' },
]
changelog = "packages/elixir/lumis/CHANGELOG.md"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"
