packages:
  - packages/javascript
  - packages/javascript/*
  - packages/javascript/lumis/native/npm/*
  - benchmarks/javascript
allowBuilds:
  '@lumis-sh/cli': true
  '@parcel/watcher': true
  better-sqlite3: true
  core-js: true
  core-js-pure: true
  esbuild: true
  sharp: true
