[package]
name = "dev"
version = "0.1.0"
publish = false
edition = "2021"
rust-version = "1.91"
license = "MIT"
homepage = "https://lumis.sh"
repository = "https://github.com/leandrocp/lumis"
authors = ["Leandro Pereira <leandro@leandro.io>"]

[workspace]

[[bin]]
name = "dev"
path = "src/main.rs"

[features]
default = []
lumis-all-languages = ["lumis/all-languages"]

[dependencies]
lumis = { path = "../lumis", default-features = false }
lumis-build = { path = "../lumis-build" }
lumis-wasm-runtime = { path = "../lumis-wasm-runtime", default-features = false }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
full_moon = "2"
glob = "0.3"
md-5 = "0.11"
regex = "1"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
toml = "1.1"
toml_edit = "0.25"
ureq = "3"
xz2 = "0.1"
wasmparser = "0.244"
