[package]
name = "dev"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "dev"
path = "src/main.rs"

[dependencies]
lumis = { path = "../lumis" }
lumis-core = { path = "../lumis-core" }
anyhow = "1"
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
full_moon = "2"
glob = "0.3"
md-5 = "0.10"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
toml_edit = "0.22"
ureq = "3"
