/**
 * Downloads pre-built .wasm files for tree-sitter parsers from npm packages.
 *
 * For the PoC we download from the tree-sitter-wasms npm registry.
 * In production, these could be built from vendored parsers via `tree-sitter build --wasm`.
 */

import fs from 'node:fs'
import path from 'node:path'
import { execSync } from 'node:child_process'

const OUT_DIR = path.resolve(import.meta.dirname, '../wasm')

// Map language names to their npm tree-sitter grammar packages
const PARSERS: Record<string, string> = {
  javascript: 'tree-sitter-javascript',
  rust: 'tree-sitter-rust',
  json: 'tree-sitter-json',
}

function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true })

  // Use a temp dir to install the npm packages and extract .wasm files
  const tmpDir = path.join(OUT_DIR, '.tmp')
  fs.mkdirSync(tmpDir, { recursive: true })

  try {
    // Install tree-sitter-wasms which bundles pre-built .wasm files
    console.log('Installing tree-sitter-wasms...')
    execSync('npm pack tree-sitter-wasms@0.1.13 --pack-destination .', {
      cwd: tmpDir,
      stdio: 'pipe',
    })

    // Extract the tarball
    const tarball = fs.readdirSync(tmpDir).find((f) => f.endsWith('.tgz'))
    if (!tarball) throw new Error('Failed to download tree-sitter-wasms')
    execSync(`tar xzf ${tarball}`, { cwd: tmpDir, stdio: 'pipe' })

    // Copy relevant .wasm files
    const wasmDir = path.join(tmpDir, 'package', 'out')
    for (const [lang, parserName] of Object.entries(PARSERS)) {
      const wasmFile = `${parserName}.wasm`
      const src = path.join(wasmDir, wasmFile)
      const dst = path.join(OUT_DIR, wasmFile)

      if (fs.existsSync(src)) {
        fs.copyFileSync(src, dst)
        const size = (fs.statSync(dst).size / 1024).toFixed(0)
        console.log(`  ${wasmFile} (${size} KB)`)
      } else {
        console.warn(`  WARNING: ${wasmFile} not found in tree-sitter-wasms`)
      }
    }
  } finally {
    // Cleanup
    fs.rmSync(tmpDir, { recursive: true, force: true })
  }

  // Generate inline WASM module for tree-sitter parser runtime
  const treeSitterWasm = path.resolve(import.meta.dirname, '../node_modules/web-tree-sitter/tree-sitter.wasm')
  if (fs.existsSync(treeSitterWasm)) {
    const wasmBytes = fs.readFileSync(treeSitterWasm)
    const base64 = wasmBytes.toString('base64')
    const size = (wasmBytes.length / 1024).toFixed(0)

    const moduleSource = [
      '// Generated by build-wasm.ts — do not edit',
      `const wasmBase64 = "${base64}"`,
      'const wasmBinary = Uint8Array.from(atob(wasmBase64), c => c.charCodeAt(0))',
      'export default wasmBinary.buffer',
      '',
    ].join('\n')

    const outPath = path.resolve(import.meta.dirname, '../src/tree-sitter-wasm.ts')
    fs.writeFileSync(outPath, moduleSource)
    console.log(`  tree-sitter-wasm.ts (${size} KB WASM → ${(base64.length / 1024).toFixed(0)} KB base64)`)
  } else {
    console.warn('  WARNING: tree-sitter.wasm not found in web-tree-sitter package')
  }
}

main()
