import type { Parser, Language, Query } from 'web-tree-sitter'

/** A style applied to a highlighted token. */
export interface Style {
  fg?: string
  bg?: string
  bold?: boolean
  italic?: boolean
  underline?: 'solid' | 'wavy' | 'double' | 'dotted' | 'dashed' | 'undercurl'
  strikethrough?: boolean
}

/** Theme JSON shape matching crates/lumis/themes/*.json */
export interface ThemeData {
  name: string
  appearance: 'light' | 'dark'
  revision?: string
  highlights: Record<string, StyleEntry>
}

/** A style entry in a theme JSON file. */
export interface StyleEntry {
  fg?: string
  bg?: string
  bold?: boolean
  italic?: boolean
  underline?: 'solid' | 'wavy' | 'double' | 'dotted' | 'dashed' | 'undercurl'
  strikethrough?: boolean
}

/** A language definition generated by the build script. */
export interface LanguageDefinition {
  id: string
  aliases: string[]
  embeddedLangs: string[]
}

/** Self-contained language bundle with metadata, queries, and WASM reference. */
export interface LanguageBundle {
  id: string
  aliases: string[]
  embeddedLangs: string[]
  highlights: string
  injections?: string
  locals?: string
  wasm: URL | string
}

/** Loaded language ready for highlighting. */
export interface LoadedLanguage {
  definition: LanguageDefinition
  parser: Parser
  language: Language
  highlightsQuery: Query
  injectionsQuery?: Query
  localsQuery?: Query
}

/** A highlight event emitted during iteration. */
export type HighlightEvent =
  | { type: 'source'; start: number; end: number }
  | { type: 'highlightStart'; scope: string }
  | { type: 'highlightEnd' }

/** A styled text segment — result of highlighting. */
export interface StyledSegment {
  text: string
  scope: string
  style: Style
}

/** The language ID used for plaintext (no syntax highlighting). */
export const PLAINTEXT_LANG_ID = 'plaintext'

// ── Formatter types ──

/** An HTML element that wraps the rendered code block. */
export interface HtmlElement {
  openTag: string
  closeTag: string
}

/** Internal formatter tag — not part of public API. */
export const FORMATTER_TAG = Symbol('formatter')

/** A configured formatter returned by htmlInline(), htmlLinked(), etc. */
export interface Formatter {
  [FORMATTER_TAG]: 'html_inline' | 'html_linked' | 'terminal'
}

export interface HtmlInlineOptions {
  lang?: string | LanguageBundle
  theme?: string | ThemeData
  preClass?: string
  italic?: boolean
  includeHighlights?: boolean
  header?: HtmlElement
}

export interface HtmlInlineFormatter extends HtmlInlineOptions, Formatter {
  [FORMATTER_TAG]: 'html_inline'
}

export interface HtmlLinkedOptions {
  lang?: string | LanguageBundle
  preClass?: string
}

export interface HtmlLinkedFormatter extends HtmlLinkedOptions, Formatter {
  [FORMATTER_TAG]: 'html_linked'
}

export interface TerminalOptions {
  lang?: string | LanguageBundle
  theme?: string | ThemeData
}

export interface TerminalFormatter extends TerminalOptions, Formatter {
  [FORMATTER_TAG]: 'terminal'
}

