[package]
name = "lumis-build"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
description = "Lumis build utilities"
keywords = ["tree-sitter", "lua", "regex", "build"]
categories = ["development-tools::build-utils"]
include = ["/src/", "/CHANGELOG.md", "/README.md", "/LICENSE"]
