[package]
name = "lumis"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

description = "Syntax Highlighter powered by Tree-sitter and Neovim themes"
keywords = ["lumis", "syntax-highlighter", "tree-sitter", "neovim"]
categories = ["text-processing"]
include = [
    "/build.rs",
    "/languages.toml",
    "/src/",
    "/vendored_parsers/tree-sitter-*/src/tree_sitter/*.h",
    "/vendored_parsers/tree-sitter-*/src/*.h",
    "/vendored_parsers/tree-sitter-*/src/*.c",
    "/vendored_parsers/tree-sitter-*/src/*.cc",
    "/vendored_parsers/tree-sitter-csv/csv/src/tree_sitter/*.h",
    "/vendored_parsers/tree-sitter-csv/csv/src/*.c",
    "/vendored_parsers/tree-sitter-comment/src/tree_sitter_comment/*.h",
    "/vendored_parsers/tree-sitter-comment/src/tree_sitter_comment/*.c",
    "/queries/README.md",
    "/queries/**/highlights.scm",
    "/queries/**/injections.scm",
    "/queries/**/locals.scm",
    "/overwrites/",
    "/css/*.css",
    "/themes/*.json",
    "/LICENSE",
    "/README.md",
    "/CHANGELOG.md",
]

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]
no-default-features = true

[features]
dev = []
default = ["all-languages"]

all-languages = [
    "lang-angular",
    "lang-asm",
    "lang-astro",
    "lang-bash",
    "lang-c",
    "lang-caddy",
    "lang-clojure",
    "lang-cmake",
    "lang-comment",
    "lang-commonlisp",
    "lang-cpp",
    "lang-csharp",
    "lang-css",
    "lang-csv",
    "lang-dart",
    "lang-diff",
    "lang-dockerfile",
    "lang-eex",
    "lang-ejs",
    "lang-elixir",
    "lang-elm",
    "lang-erb",
    "lang-erlang",
    "lang-fish",
    "lang-fsharp",
    "lang-gleam",
    "lang-glimmer",
    "lang-go",
    "lang-graphql",
    "lang-haskell",
    "lang-hcl",
    "lang-heex",
    "lang-html",
    "lang-http",
    "lang-iex",
    "lang-java",
    "lang-javascript",
    "lang-json",
    "lang-kotlin",
    "lang-latex",
    "lang-liquid",
    "lang-llvm",
    "lang-lua",
    "lang-make",
    "lang-markdown",
    "lang-markdown-inline",
    "lang-nix",
    "lang-nushell",
    "lang-objc",
    "lang-ocaml",
    "lang-perl",
    "lang-php",
    "lang-powershell",
    "lang-protobuf",
    "lang-python",
    "lang-r",
    "lang-regex",
    "lang-ruby",
    "lang-rust",
    "lang-scala",
    "lang-scss",
    "lang-sql",
    "lang-surface",
    "lang-svelte",
    "lang-swift",
    "lang-toml",
    "lang-tsx",
    "lang-typescript",
    "lang-typst",
    "lang-vim",
    "lang-vue",
    "lang-wat",
    "lang-xml",
    "lang-yaml",
    "lang-zig",
]

lang-angular = ["lumis-core/lang-angular"]
lang-asm = ["dep:tree-sitter-asm", "lumis-core/lang-asm"]
lang-astro = ["lumis-core/lang-astro"]
lang-bash = ["dep:tree-sitter-bash", "lumis-core/lang-bash"]
lang-c = ["dep:tree-sitter-c", "lumis-core/lang-c"]
lang-caddy = ["lumis-core/lang-caddy"]
lang-clojure = ["lumis-core/lang-clojure"]
lang-cmake = ["dep:tree-sitter-cmake", "lumis-core/lang-cmake"]
lang-comment = ["dep:tree-sitter-comment", "lumis-core/lang-comment"]
lang-commonlisp = ["lumis-core/lang-commonlisp"]
lang-cpp = ["dep:tree-sitter-cpp", "lumis-core/lang-cpp"]
lang-csharp = ["dep:tree-sitter-c-sharp", "lumis-core/lang-csharp"]
lang-css = ["dep:tree-sitter-css", "lumis-core/lang-css"]
lang-csv = ["lumis-core/lang-csv"]
lang-dart = ["lumis-core/lang-dart"]
lang-diff = []
lang-dockerfile = ["lumis-core/lang-dockerfile"]
lang-eex = ["lumis-core/lang-eex"]
lang-ejs = ["dep:tree-sitter-embedded-template", "lumis-core/lang-ejs"]
lang-elixir = ["dep:tree-sitter-elixir", "lumis-core/lang-elixir"]
lang-elm = ["dep:tree-sitter-elm", "lumis-core/lang-elm"]
lang-erb = ["dep:tree-sitter-embedded-template", "lumis-core/lang-erb"]
lang-erlang = ["dep:tree-sitter-erlang", "lumis-core/lang-erlang"]
lang-fish = ["lumis-core/lang-fish"]
lang-fsharp = ["dep:tree-sitter-fsharp", "lumis-core/lang-fsharp"]
lang-gleam = ["lumis-core/lang-gleam"]
lang-glimmer = ["lumis-core/lang-glimmer"]
lang-go = ["dep:tree-sitter-go", "lumis-core/lang-go"]
lang-graphql = ["lumis-core/lang-graphql"]
lang-haskell = ["dep:tree-sitter-haskell", "lumis-core/lang-haskell"]
lang-hcl = ["lumis-core/lang-hcl"]
lang-heex = ["dep:tree-sitter-heex", "lumis-core/lang-heex"]
lang-html = ["dep:tree-sitter-html", "lumis-core/lang-html"]
lang-http = ["lumis-core/lang-http"]
lang-iex = ["lumis-core/lang-iex"]
lang-java = ["dep:tree-sitter-java", "lumis-core/lang-java"]
lang-javascript = ["dep:tree-sitter-javascript", "lumis-core/lang-javascript"]
lang-json = ["dep:tree-sitter-json", "lumis-core/lang-json"]
lang-kotlin = ["lumis-core/lang-kotlin"]
lang-latex = ["lumis-core/lang-latex"]
lang-liquid = ["lumis-core/lang-liquid"]
lang-llvm = ["lumis-core/lang-llvm"]
lang-lua = ["dep:tree-sitter-lua", "lumis-core/lang-lua"]
lang-make = ["lumis-core/lang-make"]
lang-markdown = ["lumis-core/lang-markdown"]
lang-markdown-inline = ["lumis-core/lang-markdown-inline"]
lang-nix = ["dep:tree-sitter-nix", "lumis-core/lang-nix"]
lang-nushell = ["lumis-core/lang-nushell"]
lang-objc = ["dep:tree-sitter-objc", "lumis-core/lang-objc"]
lang-ocaml = ["dep:tree-sitter-ocaml", "lumis-core/lang-ocaml"]
lang-perl = ["lumis-core/lang-perl"]
lang-php = ["dep:tree-sitter-php", "lumis-core/lang-php"]
lang-powershell = ["dep:tree-sitter-powershell", "lumis-core/lang-powershell"]
lang-protobuf = ["dep:tree-sitter-proto", "lumis-core/lang-protobuf"]
lang-python = ["dep:tree-sitter-python", "lumis-core/lang-python"]
lang-r = ["dep:tree-sitter-r", "lumis-core/lang-r"]
lang-regex = ["dep:tree-sitter-regex", "lumis-core/lang-regex"]
lang-ruby = ["dep:tree-sitter-ruby", "lumis-core/lang-ruby"]
lang-rust = ["dep:tree-sitter-rust", "lumis-core/lang-rust"]
lang-scala = ["dep:tree-sitter-scala", "lumis-core/lang-scala"]
lang-scss = ["lumis-core/lang-scss"]
lang-sql = ["dep:tree-sitter-sequel", "lumis-core/lang-sql"]
lang-surface = ["lumis-core/lang-surface"]
lang-svelte = ["dep:tree-sitter-svelte-ng", "lumis-core/lang-svelte"]
lang-swift = ["dep:tree-sitter-swift", "lumis-core/lang-swift"]
lang-toml = ["dep:tree-sitter-toml-ng", "lumis-core/lang-toml"]
lang-tsx = ["dep:tree-sitter-typescript", "lumis-core/lang-tsx"]
lang-typescript = ["dep:tree-sitter-typescript", "lumis-core/lang-typescript"]
lang-typst = ["lumis-core/lang-typst"]
lang-vim = ["lumis-core/lang-vim"]
lang-vue = ["lumis-core/lang-vue"]
lang-wat = ["lumis-core/lang-wat"]
lang-xml = ["dep:tree-sitter-xml", "lumis-core/lang-xml"]
lang-yaml = ["dep:tree-sitter-yaml", "lumis-core/lang-yaml"]
lang-zig = ["dep:tree-sitter-zig", "lumis-core/lang-zig"]

[dependencies]
lumis-core = { version = "0.0.1", default-features = false }
anyhow = "1.0"
derive_builder = "0.20"
glob = "0.3"
regex = "1.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smol_str = "0.3"
streaming-iterator = "0.1"
termcolor = "1.4"
thiserror = "2"
tree-sitter = "0.25"
tree-sitter-asm = { version = "0.24.0", optional = true }
tree-sitter-bash = { version = "0.25.1", optional = true }
tree-sitter-c = { version = "0.24.1", optional = true }
tree-sitter-c-sharp = { version = "0.23.1", optional = true }
tree-sitter-cmake = { version = "0.7.1", optional = true }
tree-sitter-comment = { version = "0.3.0", optional = true }
tree-sitter-cpp = { version = "0.23.4", optional = true }
tree-sitter-css = { version = "0.25.0", optional = true }
tree-sitter-diff = "0.1.0"
tree-sitter-elixir = { version = "0.3.4", optional = true }
tree-sitter-elm = { version = "5.9.0", optional = true }
tree-sitter-embedded-template = { version = "0.25.0", optional = true }
tree-sitter-erlang = { version = "0.15.0", optional = true }
tree-sitter-fsharp = { version = "0.1.0", optional = true }
tree-sitter-go = { version = "0.25.0", optional = true }
tree-sitter-haskell = { version = "0.23.1", optional = true }
tree-sitter-heex = { version = "0.8.1", optional = true }
tree-sitter-highlight = "0.25"
tree-sitter-html = { version = "0.23.2", optional = true }
tree-sitter-java = { version = "0.23.5", optional = true }
tree-sitter-javascript = { version = "0.25.0", optional = true }
tree-sitter-json = { version = "0.24.8", optional = true }
tree-sitter-language = "0.1.7"
tree-sitter-lua = { version = "0.4.1", optional = true }
tree-sitter-nix = { version = "0.3.0", optional = true }
tree-sitter-objc = { version = "3.0.2", optional = true }
tree-sitter-ocaml = { version = "0.24.2", optional = true }
tree-sitter-php = { version = "0.24.2", optional = true }
tree-sitter-powershell = { version = "0.25.10", optional = true }
tree-sitter-proto = { version = "0.4.0", optional = true }
tree-sitter-python = { version = "0.25.0", optional = true }
tree-sitter-r = { version = "1.2.0", optional = true }
tree-sitter-regex = { version = "0.25.0", optional = true }
tree-sitter-ruby = { version = "0.23.1", optional = true }
tree-sitter-rust = { version = "0.24.0", optional = true }
tree-sitter-scala = { version = "0.24.0", optional = true }
tree-sitter-sequel = { version = "0.3.11", optional = true }
tree-sitter-svelte-ng = { version = "1.0.2", optional = true }
tree-sitter-swift = { version = "0.7.1", optional = true }
tree-sitter-toml-ng = { version = "0.7.0", optional = true }
tree-sitter-typescript = { version = "0.23.2", optional = true }
tree-sitter-xml = { version = "0.7.0", optional = true }
tree-sitter-yaml = { version = "0.7.2", optional = true }
tree-sitter-zig = { version = "1.1.2", optional = true }
v_htmlescape = "0.15"

[build-dependencies]
cc = "1"
glob = "0.3"
lumis-build = { version = "0.0.1" }
prettyplease = "0.2"
proc-macro2 = "1"
quote = "1"
rayon = "1"
serde = { version = "1", features = ["derive"] }
syn = { version = "2.0", features = ["full", "parsing"] }
toml = "0.8"

[dev-dependencies]
pretty_assertions = "1.4"
