allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@lumis-sh/wasm-html@0.26.3"
  - "@lumis-sh/wasm-javascript@0.26.3"
  - "@lumis-sh/lumis-native-darwin-arm64@0.7.0"
  - "@lumis-sh/lumis-native-darwin-x64@0.7.0"
  - "@lumis-sh/lumis-native-linux-arm64-gnu@0.7.0"
  - "@lumis-sh/lumis-native-linux-arm64-musl@0.7.0"
  - "@lumis-sh/lumis-native-linux-x64-gnu@0.7.0"
  - "@lumis-sh/lumis-native-linux-x64-musl@0.7.0"
  - "@lumis-sh/lumis-native-win32-arm64-msvc@0.7.0"
  - "@lumis-sh/lumis-native-win32-x64-msvc@0.7.0"
  - "@lumis-sh/lumis@0.7.0"
  - "@lumis-sh/themes@0.3.0"
  - "@lumis-sh/wasm-bundle-full@0.1.1"
