/**
 * Generates JavaScript language metadata from languages.toml.
 *
 * Parser bytes, queries, integrity metadata, and exact versions belong to the
 * independently released @lumis-sh/wasm-* packages, not the runtimes.
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { parse as parseToml } from "smol-toml";

const WORKSPACE_ROOT = path.resolve(import.meta.dirname, "../../../..");
const OUT_DIR = path.resolve(import.meta.dirname, "../langs");
const GENERATED_DIR = path.resolve(import.meta.dirname, "../src/generated");
const BUNDLES_DIR = path.resolve(import.meta.dirname, "../bundles");

const LANGUAGES_TOML = path.join(WORKSPACE_ROOT, "languages.toml");
const CATALOG_RS = path.join(WORKSPACE_ROOT, "crates/lumis-wasm-runtime/src/catalog.rs");

// The pins live in the generated Rust catalog, which `mise run langs-gen-catalog`
// resolves from the registry. Reading them here keeps one source of truth rather
// than a second list that could disagree about which version a runtime expects.
function pinnedVersions(): Map<string, string> {
  const source = fs.readFileSync(CATALOG_RS, "utf-8");
  const versions = new Map<string, string>();
  const pattern = /package_name:\s*"([^"]+)",\s*\n\s*version:\s*"([^"]+)"/g;
  for (const match of source.matchAll(pattern)) versions.set(match[1]!, match[2]!);
  if (versions.size === 0) {
    throw new Error(`no pinned versions found in ${CATALOG_RS}; run mise run langs-gen-catalog`);
  }
  return versions;
}

interface ParserEntry {
  aliases?: string[];
  emacs?: string[];
  shebang?: string[];
  wasm_name?: string;
  display_name?: string;
  variant?: string;
  globs?: string[];
}

interface BundleEntry {
  parsers: string[] | "all";
}

interface LanguagesToml {
  parsers: Record<string, ParserEntry>;
  bundles?: Record<string, BundleEntry>;
}

function readLanguagesToml(): LanguagesToml {
  const text = fs.readFileSync(LANGUAGES_TOML, "utf-8");
  return parseToml(text) as unknown as LanguagesToml;
}

function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const config = readLanguagesToml();
  const versions = pinnedVersions();
  const expectedLanguageIds = new Set([...Object.keys(config.parsers), "plaintext"]);

  for (const entry of fs.readdirSync(OUT_DIR)) {
    if (!entry.endsWith(".ts")) continue;
    const id = path.parse(entry).name;
    if (expectedLanguageIds.has(id)) continue;
    fs.unlinkSync(path.join(OUT_DIR, entry));
    console.log(`  removed stale language: langs/${entry}`);
  }

  for (const [id, entry] of Object.entries(config.parsers)) {
    const wasmName = entry.wasm_name || `tree-sitter-${id}`;
    const packageName = `@lumis-sh/wasm-${wasmName.replace(/^tree-sitter-/, "")}`;
    const aliases = entry.aliases || [];

    const version = versions.get(packageName);
    if (version === undefined) {
      throw new Error(`no pinned version for ${packageName}; run mise run langs-gen-catalog`);
    }

    const module = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguagePackageHandle } from '../src/types.js'

const language: LanguagePackageHandle = {
  id: ${JSON.stringify(id)},
  aliases: ${JSON.stringify(aliases)},
  packageName: ${JSON.stringify(packageName)},
  version: ${JSON.stringify(version)},
}

export default language
`;

    fs.writeFileSync(path.join(OUT_DIR, `${id}.ts`), module);
    console.log(`  ${id}: langs/${id}.ts`);
  }

  const plaintextModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { PlaintextLanguage } from '../src/types.js'

const language: PlaintextLanguage = {
  id: "plaintext",
  aliases: ["text", "txt", "plain"],
}

export default language
`;
  fs.writeFileSync(path.join(OUT_DIR, "plaintext.ts"), plaintextModule);
  console.log(`  plaintext: langs/plaintext.ts`);
  // Generate language metadata
  const languageEntries: {
    id: string;
    name: string;
    aliases: string[];
    extensions: string[];
    globs: string[];
    emacsModes: string[];
    shebangs: string[];
  }[] = [];

  for (const [id, entry] of Object.entries(config.parsers)) {
    const aliases = entry.aliases || [];
    const variant = entry.variant || titlecase(id);
    const name = entry.display_name || variant;
    const globs = entry.globs || [];
    const extensions = globs.filter((g) => g.startsWith("*."));
    const emacsModes = entry.emacs || [];
    const shebangs = entry.shebang || [];

    languageEntries.push({ id, name, aliases, extensions, globs, emacsModes, shebangs });
  }

  // Add plaintext
  languageEntries.push({
    id: "plaintext",
    name: "Plain Text",
    aliases: ["text", "txt", "plain"],
    extensions: [],
    globs: [],
    emacsModes: ["fundamental", "text"],
    shebangs: [],
  });

  fs.mkdirSync(GENERATED_DIR, { recursive: true });

  const packageVersions: Record<string, string> = {};
  for (const [pkg, version] of versions) packageVersions[pkg] = version;
  const packageVersionsModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
// Mirrors \`catalog::pinned_version\` in crates/lumis-wasm-runtime.
export const PACKAGE_VERSIONS: Record<string, string> = ${JSON.stringify(packageVersions, null, 2)}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "package-versions.ts"), packageVersionsModule);
  console.log(`  package versions: src/generated/package-versions.ts`);

  const languageMetaModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguageInfo } from '../types.js'

export const LANGUAGES: LanguageInfo[] = ${JSON.stringify(languageEntries, null, 2)}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "languages-meta.ts"), languageMetaModule);
  console.log(`  languages metadata: src/generated/languages-meta.ts`);

  const exactLanguageMap: Record<string, string> = {};
  const emacsModeMap: Record<string, string> = {};
  const shebangMap: Record<string, string> = {};
  const globMatchers: Array<{ id: string; glob: string }> = [];

  for (const language of languageEntries) {
    exactLanguageMap[language.id.toLowerCase()] = language.id;

    for (const alias of language.aliases) {
      exactLanguageMap[alias.toLowerCase()] = language.id;
    }

    for (const mode of language.emacsModes) {
      emacsModeMap[mode.toLowerCase()] = language.id;
    }

    for (const shebang of language.shebangs) {
      shebangMap[shebang.toLowerCase()] = language.id;
    }

    for (const glob of language.globs) {
      globMatchers.push({ id: language.id, glob: glob.toLowerCase() });
    }
  }

  const languageDetectionModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
export const EXACT_LANGUAGE_MAP: Record<string, string> = ${JSON.stringify(exactLanguageMap, null, 2)}

export const EMACS_MODE_MAP: Record<string, string> = ${JSON.stringify(emacsModeMap, null, 2)}

export const SHEBANG_MAP: Record<string, string> = ${JSON.stringify(shebangMap, null, 2)}

export const GLOB_MATCHERS: Array<{ id: string; glob: string }> = ${JSON.stringify(globMatchers, null, 2)}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "language-detection.ts"), languageDetectionModule);
  console.log(`  language detection: src/generated/language-detection.ts`);

  const languageLoaderEntries = [...Object.keys(config.parsers), "plaintext"]
    .map((id) => `  ${JSON.stringify(id)}: () => import('../../langs/${id}.js'),`)
    .join("\n");

  const languageLoadersModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { Language } from '../types.js'

export const LANGUAGE_LOADERS: Record<string, () => Promise<{ default: Language }>> = {
${languageLoaderEntries}
}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "language-loaders.ts"), languageLoadersModule);
  console.log(`  language loaders: src/generated/language-loaders.ts`);

  // Generate theme metadata
  const THEMES_SRC = path.join(WORKSPACE_ROOT, "themes");
  const themeEntries: { name: string; appearance: string }[] = [];

  for (const file of fs
    .readdirSync(THEMES_SRC)
    .filter((f) => f.endsWith(".json"))
    .sort()) {
    const json = fs.readFileSync(path.join(THEMES_SRC, file), "utf-8");
    const data = JSON.parse(json);
    if (data.name && data.appearance) {
      themeEntries.push({ name: data.name, appearance: data.appearance });
    }
  }

  const themeMetaModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { ThemeInfo } from '../types.js'

export const THEMES: ThemeInfo[] = ${JSON.stringify(themeEntries, null, 2)}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "themes-meta.ts"), themeMetaModule);
  console.log(`  themes metadata: src/generated/themes-meta.ts`);

  // Generate bundle files
  fs.mkdirSync(BUNDLES_DIR, { recursive: true });

  const allParserIds = Object.keys(config.parsers);
  const expectedBundles = new Set(Object.keys(config.bundles ?? {}));

  for (const entry of fs.readdirSync(BUNDLES_DIR)) {
    if (!entry.endsWith(".ts")) continue;
    const bundleName = path.parse(entry).name;
    if (expectedBundles.has(bundleName)) continue;
    fs.unlinkSync(path.join(BUNDLES_DIR, entry));
    console.log(`  removed stale bundle: bundles/${entry}`);
  }

  for (const [bundleName, bundleEntry] of Object.entries(config.bundles ?? {})) {
    const parserIds = bundleEntry.parsers === "all" ? allParserIds : bundleEntry.parsers;
    const aliases: Record<string, string[]> = {};

    for (const id of parserIds) {
      const entry = config.parsers[id];
      aliases[id] = entry?.aliases ?? [];
    }

    // Always include plaintext
    if (!parserIds.includes("plaintext")) {
      aliases["plaintext"] = ["text", "txt", "plain"];
    }

    const allIds = [...parserIds];
    if (!allIds.includes("plaintext")) {
      allIds.push("plaintext");
    }

    const entries = allIds
      .map((id) => {
        const a = JSON.stringify(aliases[id] ?? []);
        return `  ${JSON.stringify(id)}: lazy(${JSON.stringify(id)}, ${a}, () => import("../langs/${id}.js")),`;
      })
      .join("\n");

    const bundleModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguageBundle } from '../src/types.js'
import { lazy } from '../src/bundle-helpers.js'

export const bundledLanguages: LanguageBundle = {
${entries}
}
`;

    fs.writeFileSync(path.join(BUNDLES_DIR, `${bundleName}.ts`), bundleModule);
    console.log(`  bundle ${bundleName}: bundles/${bundleName}.ts (${allIds.length} languages)`);
  }
}

function titlecase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

main();
// Only bundles/ is committed; langs/ and src/generated are gitignored build output.
execFileSync("oxfmt", [BUNDLES_DIR], { stdio: "inherit" });
