name: Elixir Hex Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/elixir/lumis
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          elixir-version: "1.19"

      - run: mix deps.get
        env:
          LUMIS_BUILD: "1"

      - name: Generate checksums
        run: mix rustler_precompiled.download Lumis.Native --all --print
        env:
          LUMIS_BUILD: "1"

      - name: Publish to Hex
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
          LUMIS_BUILD: "1"
