name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'knope/release'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN != '' && secrets.RELEASE_TOKEN || github.token }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          token: ${{ secrets.RELEASE_TOKEN != '' && secrets.RELEASE_TOKEN || github.token }}

      - uses: knope-dev/action@v2.1.2
        with:
          version: 0.22.4

      - name: Create tags and GitHub releases
        run: knope release --verbose
